#define OAK_MAX_PLAYERS 1000
#define OAK_MAX_VEHICLES 4000
#define OAK_MAX_WEAPON_DROPS 10
#define OAK_MAX_DOORS 100
#define OAK_MAX_NPCS 100
#define OAK_MAX_ENTITIES (OAK_MAX_PLAYERS+OAK_MAX_WEAPON_DROPS+OAK_MAX_VEHICLES+OAK_MAX_DOORS+OAK_MAX_NPCS)

#define OAK_TICK_DELAY 32

enum {
    ENTITY_INTERPOLATED = 1 << 10,
};

// TODO: remove
enum {
    TYPE_PLAYER,
    TYPE_VEHICLE,
    TYPE_WEAPONDROP,
    TYPE_DOOR,
};

typedef enum {
    OAK_PLAYER,
    OAK_VEHICLE,
    OAK_WEAPONDROP,
    OAK_DOOR,
    OAK_NPC,
    OAK_ENTITY_TYPE_LAST,
} oak_type;


enum {
    REJECTION_VERSION,
    REJECTION_WH,
    REJECTION_BANNED,
};
