name: release-delivery
on:
  create:
    tags:
       - '*'
jobs:
  deploy-win:
    name: Deploy Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure the build system
        run: ./premake.sh.bat

      - name: Run build on windows
        run: cd Build && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild Oakwood.sln /p:Configuration="Production" /p:PlatformToolset="v142"

      - name: Combine client assets
        run: cd Scripts && "ship_client.bat"

      - name: Compress client assets
        run: cd Shipping && 7z a -tzip Client.zip Client

      - name: Combine launcher assets
        run: cd Scripts && "ship_launcher.bat"

      - name: Compress launcher assets
        run: cd Shipping && 7z a -tzip Launcher.zip Launcher

      - name: Upload assets to the release (launcher)
        uses: ./.github/actions/release-upload
        with:
          input: ./Shipping/Launcher.zip
          output: oakwood-launcher-v{v}-win32.zip
        env:
          GITHUB_TAG: ${{ github.ref }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets to the release (client)
        uses: ./.github/actions/release-upload
        with:
          input: ./Shipping/Client.zip
          output: oakwood-client-v{v}-win32.zip
        env:
          GITHUB_TAG: ${{ github.ref }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets to the release (server)
        uses: ./.github/actions/release-upload
        with:
          input: ./Bin/Production/OakwoodServer.exe
          output: oakwood-server-v{v}-win32.exe
        env:
          GITHUB_TAG: ${{ github.ref }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-lin:
    name: Deploy Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install deps
        run: sudo apt install -y libnanomsg-dev

      - name: Configure the build system
        run: ./premake.sh.bat

      - name: Run build
        run: cd Build && config=release make

      - name: Upload assets to the release (server)
        uses: ./.github/actions/release-upload
        with:
          input: ./Bin/Release/OakwoodServer
          output: oakwood-server-v{v}-lin64
        env:
          GITHUB_TAG: ${{ github.ref }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-mac:
    name: Deploy macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install deps
        run: brew install nanomsg

      - name: Configure the build system
        run: ./premake.sh.bat

      - name: Run build
        run: cd Build && config=release make

      - name: Upload assets to the release (server)
        uses: ./.github/actions/release-upload
        with:
          input: ./Bin/Release/OakwoodServer
          output: oakwood-server-v{v}-mac64
        env:
          GITHUB_TAG: ${{ github.ref }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Send announcement
    needs: [deploy-mac, deploy-lin, deploy-win]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Send notification
        uses: ./.github/actions/discord-notification
        if: success()
        with:
          type: release
        env:
          DISCORD_WEBHOOK_CHANNEL: 518087246650540043
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      - name: Bust the cache
        run: curl https://releases.mafiahub.dev/api?cache=bust
